version: "3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-netwwork
  backend:
    build:
      context: ./backend
    container_name: "backend"
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mern-netwwork

networks:
  mern-netwwork:
    driver: bridge
